version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: grammy-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grammy_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - grammy-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 3

  grammy-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grammy-bot
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/grammy_bot
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grammy-network

volumes:
  postgres_data:
    driver: local

networks:
  grammy-network:
    driver: bridge
