version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: grammy-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - grammy-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 3

  grammy-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grammy-bot
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - ADMIN_TELEGRAM_IDS=${ADMIN_TELEGRAM_IDS}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grammy-network

volumes:
  postgres_data:
    driver: local

networks:
  grammy-network:
    driver: bridge
